name: 'Flow Coverage Linter'
description: 'Check to make sure all your code is really covered!'
runs:
  using: 'node10'
  main: 'dist/flow-coverage.js'
inputs:
  files:
    required: true
    description: Pass in a list of files to check (separated by ':::')! Probably from files-changed-action
  flow-bin:
    required: false
    description: 'Path to your flow binary, defaults to node_modules/.bin/flow'
branding:
  icon: check-circle
  color: red