name: 'Flow Coverage Linter'
description: 'Check to make sure all your code is really covered!'
runs:
  using: 'node12'
  main: 'dist/action/index.js'
inputs:
  flow-bin:
    required: true
    description: 'Path to your flow library, probably node_modules/.bin/flow'
  custom-working-directory:
    required: false
    description: 'Path to your working directory, uses `.` if not provided'
  check-run-subtitle:
    required: false
    description: 'A subtitle to add to the check run when annotations are passed back to avoid overwriting each other'
branding:
  icon: check-circle
  color: red
