name: Autofixers

# Our autofixers are all put together in a single job (called autofix), to
# reduce churn

on:
  - pull_request

include:
  - _setup.yml

jobs:
  autofix:
    runs-on: ubuntu-latest
    if: github.actor != 'khan-actions-bot'

    steps:
    ## Rebuild workflow file
    - name: Rebuild github actions workflow
      setup: yarn
      paths: .github/workflow-templates/**
      run: yarn make-workflows

    - name: Run prettier
      setup: yarn
      run: node ./node_modules/actions-utils/list-changed-files.js | grep '.*\.js$' | xargs npm run -s format-files

    - name: Rebuild our distributed files
      setup: yarn
      run: yarn run dist

    - uses: Khan/autofix-commit-action@main
      env:
        GITHUB_TOKEN: ${{ secrets.KHAN_ACTIONS_BOT_TOKEN }}
