name: Run on itself!
'on':
  - pull_request
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - uses: Khan/files-changed-action@master
        id: files
      - uses: Khan/flow-coverage-action@example-wrong
        with:
          files: ${{ steps.files.outputs.files }}
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: yarn flow

